---
contacts:
  telegram: 'https://t.me/x88FFA277'
  twitter: 'https://twitter.com/0x88FFA277'
  github: 'https://github.com/lbr77'
  bangumi: 'https://bgm.tv/user/lbr77'
  steam: 'https://steamcommunity.com/id/stevelbr/'
  mail: 'mailto:me@nvme0n1p.dev'
friends:
  - name: 高科技的指挥中心
    desc: 
    url: https://blog.hightechbrain.net/


sponsorship:
  - name: 无
    amount: 
    msg: 
